version: '3'

services:
  db:
    image: tenforce/virtuoso:${VIRTUOSO_IMAGE_TAG:-latest}
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
      VIRT_Parameters_DirsAllowed: "., /usr/local/virtuoso-opensource/share/virtuoso/vad, /tmp/data"
    volumes:
      - ./data/virtuoso:/data
      - ${SRC_DATA_DIR:-./}:/tmp/data

  spang:
    image: "hchiba1/spang:2.1.0"
    depends_on:
      - "db"
    volumes:
      - ./data/spang:/data 
