version: '3'

services:
  db:
    image: tenforce/virtuoso:${VIRTUOSO_IMAGE_TAG:-latest}
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data

  spang-test:
    image: "hchiba1/spang"
    depends_on:
      - "db"
    volumes:
      - ./data/spang:/data 
